spring.application.name=ConsultorioDental

# BD
spring.datasource.url=jdbc:mysql://localhost:3306/sis_den
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT las variables de util
jwt.secret=mi_clave_super_segura_12345678901234567890
jwt.expiration=28800000


# RECOMENDADO
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# OPCIONAL
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG